services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: ["postgres", "-c", "checkpoint_timeout=10min"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_default
volumes:
  postgres_data:
networks:
  n8n_default:
    external: true
