services:
  postgres:
    image: postgres:17.11
    restart: always

    environment:
      POSTGRES_USER: n8n_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: n8n_db

    command:
      - postgres
      - -c
      - checkpoint_timeout=10min

    volumes:
      - postgres17_data:/var/lib/postgresql/data

    networks:
      - n8n_default

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U n8n_user -d n8n_db
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres17_data:
    external: true

networks:
  n8n_default:
    external: true