services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=n8n_user
      - POSTGRES_PASSWORD=Alex_197754
      - POSTGRES_DB=n8n_db
    command: ["postgres", "-c", "checkpoint_timeout=10min"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_default
volumes:
  postgres_data:
networks:
  n8n_default:
    external: true
